print("New")
print("File")
print("Created")
print("Name")
print("Class")
print("Address")
print("Country")
print("Age")
print("City")
print("Orange")
print("One Piece")
print("Bleach")
print("Successfull")