name = input("What is your name ?")
age = input("Enter your age : ")
standard = input("Enter your Class :")
address = input("Enter address : ")
country = input("Enter Country name : ")
print("Hello :",name)
print()
print("Age :",age)
print()
print("Class :", standard)
print()
print("Address :", address)
print()
print("Country :", country)
print()