name = input("What is your name ?")
age = input("Enter your age : ")
standard = input("Enter your Class :")
address = input("Enter address : ")
print("Hello :",name)
print("Age :",age)
print("Class :", standard)
print("Address :", address)