name = input("What is your name ?")
age = input("Enter your age : ")
standard = input("Enter your Class :")
address = input("Enter address : ")
country = input("Enter Country name : ")
height = float(input("Enter your height : "))
weight = float(input("Enter your weighht : "))
movie = input("Enter movie name : ")
team = input("Enter your favourite team : ")
print("Hello :",name)
print()
print("Age :",age)
print()
print("Class :", standard)
print()
print("Address :", address)
print()
print("Country :", country)
print()
print("Height :", height)
print()
print("Weight :", weight)
print()
print(f"Movie is : {movie}")
print()
print(f"Team : {team}")